def Convert(string):
	li = list(string.split(","))
	return li
def tdp():
    import time
    print(".", end="")
    time.sleep(0.25)
    print(".", end="")
    time.sleep(0.25)
    print(".", end="")
    time.sleep(0.25)
    print(".", end="")
    time.sleep(0.25)
    print(".", end="")
    time.sleep(0.30)
def gobye():
    import time
    print( * ".")
    time.sleep(0.25)
    print(2* ".")
    time.sleep(0.25)
    print(3 * ".")
    time.sleep(0.25)
    print(4 * ".")
    time.sleep(0.25)
    print(5*".")
    time.sleep(0.25)
    print("G", end="")
    time.sleep(0.25)
    print("O", end="")
    time.sleep(0.25)
    print("O", end="")
    time.sleep(0.25)
    print("D", end="")
    time.sleep(0.25)
    print("B", end="")
    time.sleep(0.30)
    print("Y", end="")
    time.sleep(0.25)
    print("E")
    time.sleep(0.25)
    print(5*"." )
    time.sleep(0.25)
    print(4*".")
    time.sleep(0.25)
    print(3*".")
    time.sleep(0.25)
    print(2*".")
    time.sleep(0.25)
    print(".")
def tfp():
    import time
    print("                                                              ", end="    ")
    time.sleep(0.40)
    print("T", end="")
    time.sleep(0.25)
    print("H", end="")
    time.sleep(0.25)
    print("A", end="")
    time.sleep(0.25)
    print("N", end="")
    time.sleep(0.25)
    print("K", end="")
    time.sleep(0.25)
    print("S ", end="")
    time.sleep(0.25)
    print("F", end="")
    time.sleep(0.25)
    print("O", end="")
    time.sleep(0.25)
    print("R ", end="")
    time.sleep(0.25)
    print("P", end="")
    time.sleep(0.25)
    print("L", end="")
    time.sleep(0.25)
    print("A", end="")
    time.sleep(0.25)
    print("Y", end="")
    time.sleep(0.25)
    print("I", end="")
    time.sleep(0.25)
    print("N", end="")
    time.sleep(0.25)
    print("G", end="")
def stars():
    import time
    print(*".")
    time.sleep(0.25)
    print(2 * ".")
    time.sleep(0.25)
    print(3 * ".")
    time.sleep(0.25)
    print(4 * ".")
    time.sleep(0.25)
    print(5 * ".")
    time.sleep(0.25)
    print(4 * ".")
    time.sleep(0.25)
    print(3 * ".")
    time.sleep(0.25)
    print(2 * ".")
    time.sleep(0.25)
    print(".")
def delay(arg,delay):
    import time
    kl=Convert(arg)
    for items in kl:
        print(items,end="")
        time.sleep(delay)


